### ISSUE TITLE
[Feature requests] Add PKEYs out for IB, AN, SSH

### ISSUE THREAD

**Issue by vermagit** [Azure/azhpc-diagnostics#23]
If not already present, output of **PKEYS** on the VM:
cat /sys/class/infiniband/mlx5_0/ports/1/pkeys/*

Is there a **direct test** to check if Accelerated Networking is enabled vs not? Not sure if this is in the VM metadata. Though indirectly, this is discernible through lspci, ibv_devinfo etc.

Additionally (unrelated to this ask), how can we add info if the VM is **publicly accessible (over SSH, public IP, port 22 open**)? This may be relevant to know if we can have direct access to VM (with customer consent) or will need to coordinate VM access with customer.

**Comment by tlcyr4** [comment]
For the pkeys: see #19 

For the Accelerated Networking, in a comment on this PR:  #24 @jithinjosepkl brings up potential issues AN will bring, so that will likely be its own Issue soon

For SSH, I don't think it would be too hard to check is sshd is running locally and whatever else is local to the system, but there would be other obstacles like network security rules that would block the connection. I'm also not sure I understand the proper protocol going on between Azure engineers and the customer in that scenario well enough to design the feature without some more direction.

**Comment by vermagit** [comment]
I agree. The 3rd ask is a bit tricky to cover adequately with external factors making it complicated. Perhaps best to leave this out.

On 2nd, I guess we'll take lspci etc. as proxies for AN.

Thanks for #1.
